export const GET_ERRORS = 'GET_ERRORS';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GET_LIST = 'GET_PROFILE';
export const LIST_LOADING = 'PROFILE_LOADING';
export const LIST_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const SET_CURRENT_LIST = 'SET_CURRENT_LIST';
export const CLEAR_CURRENT_LIST = 'CLEAR_CURRENT_PROFILE';
export const GET_LISTS = 'GET_PROFILES';
export const SET_LIST = 'SET_PROFILE';
